services:
  - type: web
    name: Learning_Progress_Tracker
    env: python
    buildCommand: poetry install --no-dev
    startCommand: poetry run python -m your_app_module
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4